apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapp1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: serverapp1
  template:
    metadata:
      labels:
        app: serverapp1
    spec:
      containers:
      - name: serverapp1
        image: prayag10/serverapp1
        ports:
        - containerPort: 4000
